#----------------------------------------
# Status bar
#----------------------------------------

# Color definitions:
# https://jonasjacek.github.io/colors/
# https://commons.wikimedia.org/wiki/File:Xterm_256color_chart.svg
set -g status-style fg=colour161,bg=colour234,bright # deeppink3, grey11
set -g status-left-length 30
set -g window-status-current-style bg=colour241,fg=colour046 # grey39, green1
set -g status-left '#[fg=colour172][#(whoami)@#h] #[fg=black,bright]• '
set -g status-right '#[fg=black,bright]• #[fg=magenta]#(cut -d " " -f1-3 /proc/loadavg) #[fg=black,bright]• #[fg=colour039]%a, %b %d #[fg=black,bright]• #[fg=colour70]%R'
set -g message-style fg=black,bg=colour203 # indianred1

set -sg escape-time 1
set-option -g focus-events on

set -g mode-keys vi
set -g history-limit 10000000

# y and p as in vim
bind Escape copy-mode
unbind p
bind p paste-buffer
bind-key -T copy-mode-vi v     send -X begin-selection
bind-key -T copy-mode-vi Y     send -X copy-end-of-line
bind-key -T copy-mode-vi V     send -X rectangle-toggle
bind-key -T copy-mode-vi PPage send -X page-up
bind-key -T copy-mode-vi NPage send -X page-down
bind-key -T copy-mode-vi y     send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"
bind-key -T copy-mode-vi Enter send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# easy-to-remember split pane commands
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind-key = select-layout even-vertical
bind-key + select-layout even-horizontal
unbind '"'
unbind %
# moving between panes with vim movement keys
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# moving between windows with vim movement keys
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+
bind -r 'Space' select-window -t :+
bind -r 'BSpace' select-window -t :-
bind b last-window

# resize panes with vim movement keys
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

setw -g aggressive-resize on
set-option -g renumber-windows on

# auto window rename
set-window-option -g automatic-rename
set -g update-environment "SSH_CONNECTION SSH_CLIENT"

# reload conf
bind r source-file ~/.tmux.conf
